name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'v1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get-version
        run: |
          $VERSION="${{ github.event.inputs.release_name }}" -replace '^.*/ '
          "version=$VERSION" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Publish to WinGet
        id: publish-winget
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Package.Identifier
          version: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
