name: Update winget manifest

on:
  workflow_dispatch:
    args:
      version:
        description: 'Version of the application to update'
        required: true

jobs:
  check-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Run Komac
        uses: michidk/run-komac@v2
        with:
          komac-version: 2.16.0
          args: 'update Kesomannen.Gale --version ${{ github.event.inputs.version }} --urls https://github.com/Kesomannen/gale/releases/download/${{ github.event.inputs.version }}/Gale_${{ github.event.inputs.version }}_x64_en-US.msi --submit'
